### ISSUE TITLE
Notification position

### ISSUE THREAD

**Issue by ponasromas** [rafalm99/page-notifications#1]
Hello,

I'am using your script for notifications in few my projects. Really beautiful and simple. But I miss option to control notification position on the page. If you will have any spare time - it would be awesome to have it.

**Comment by rmichaluszek** [comment]
Yeah, ill swe what i can do. Do you just wants to się top,down,right,left
etc or somerhing rose?

niedz., 19 sty 2020, 14:13 użytkownik ponasromas <notifications@github.com>
napisał:

**Comment by ponasromas** [comment]
Top (left/middle/right) and Bottom (left/middle/right). Thank you!

**Comment by rmichaluszek** [comment]
With the top i will need more timer as i would revert all the animstions,
positions etc. But bottom left,middle,right will be for sure

wt., 21 sty 2020, 13:18 użytkownik ponasromas <notifications@github.com>
napisał:

**Comment by rmichaluszek** [comment]
All done, check out the new 1.0.3 release:
[version 1.0.3](https://github.com/rmichaluszek/page-notifications/releases/tag/1.0.3)

**Usage:**
In constructor:
`var pn = new PageNotifications({position:'top-right'})`
you can use attribute 'position' with states:
-top-left
-top-middle
-top-right
-bottom-left
-bottom-middle
-bottom-right

**Comment by ponasromas** [comment]
Fantastic! Thank you.
